version: '3.8'

services:
  depato-lease:
    build: .
    container_name: depato-lease-app
    ports:
      - "81:81"      # 前端端口
      - "8081:8081"  # 后端端口
      - "9000:9000"  # MinIO API端口
      - "9001:9001"  # MinIO Console端口
    volumes:
      - mysql_data:/var/lib/mysql
      - redis_data:/var/lib/redis
      - minio_data:/opt/minio/data
    environment:
      - MYSQL_ROOT_PASSWORD=
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:
  redis_data:
  minio_data: 
